"""add_allowed_emails

Revision ID: c192f2cc1ef6
Revises: e37c81dd031f
Create Date: 2026-05-09 04:35:51.966699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c192f2cc1ef6'
down_revision: Union[str, None] = 'e37c81dd031f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allowed_emails',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('allowed_emails')
    # ### end Alembic commands ###
